enum FilmsActionTypes {
  /** Films info */
  FETCH_FILMS_INFO = 'FETCH_FILMS_INFO',
  FETCH_ONE_FILM_INFO = 'FETCH_ONE_FILM_INFO',
  SET_FILMS_INFO = 'SET_FILMS_INFO',
  SET_ONE_FILM_INFO = 'SET_ONE_FILM_INFO',
  CLEAR_FILMS_INFO = 'CLEAR_FILMS_INFO',
  CLEAR_ONE_FILM_INFO = 'CLEAR_ONE_FILM_INFO',

}

export default FilmsActionTypes;
