enum CharacterActionTypes {
  /** Character info */
  FETCH_CHARACTERS_INFO = 'FETCH_CHARACTERS_INFO',
  FETCH_ONE_CHARACTER_INFO = 'FETCH_ONE_CHARACTER_INFO',
  SET_CHARACTERS_INFO = 'SET_CHARACTERS_INFO',
  SET_ONE_CHARACTER_INFO = 'SET_ONE_CHARACTER_INFO',
  CLEAR_CHARACTERS_INFO = 'CLEAR_CHARACTERS_INFO',
  CLEAR_ONE_CHARACTER_INFO = 'CLEAR_ONE_CHARACTER_INFO',

}

export default CharacterActionTypes;
